spring.application.name=retaillab-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/retaillab
spring.datasource.username=retaillab
spring.datasource.password=retaillab

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
